name: .NET

on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: ./
      SOLUTION_FILE: Blazor boilerplate.sln
      CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_PATH }}${{ env.SOLUTION_FILE }}"
      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}${{ env.SOLUTION_FILE }}" --configuration ${{ env.CONFIGURATION }}  --no-restore
      - name: Test
        run: dotnet test "${{ env.PROJECT_PATH }}${{ env.SOLUTION_FILE }}" --no-build --verbosity normal
